version: '3'
services:

  quality-trace:
    image: intelops/quality-trace:${TAG:-latest}
    platform: linux/amd64
    volumes:
      - ./quality-trace/quality-trace.config.yaml:/app/quality-trace.yaml
      - ./quality-trace/quality-trace-provision.yaml:/app/provision.yaml
    command: --provisioning-file /app/provision.yaml
    ports:
      - 11633:11633
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:11633"]
      interval: 1s
      timeout: 3s
      retries: 60
    environment:
      TRACETEST_DEV: ${TRACETEST_DEV}

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 60

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.59.0
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./quality-trace/collector.config.yaml:/otel-local-config.yaml
