apiVersion: v2
actions:
- name: "Run quality-trace on your service"
  events:
    - name: "sh.keptn.event.test.triggered"
  tasks:
    - name: "Run quality-trace"
      files:
        - data/test-definition.yaml
        - data/quality-trace-cli-config.yaml
      image: "intelops/quality-trace:latest"
      cmd:
        - quality-trace
      args:
        - --config
        - /keptn/data/quality-trace-cli-config.yaml
        - run
        - test
        - --file
        - /keptn/data/test-definition.yaml

