version: "3.2"
services:
  qualityt-race:
    restart: unless-stopped
    image: intelops/quality-trace:${TAG:-latest}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build:
      context: .
    volumes:
      - type: bind
        source: ./local-config/quality-trace.config.yaml
        target: /app/quality-trace.yaml
      - type: bind
        source: ./local-config/quality-trace.provision.yaml
        target: /app/provisioning.yaml
    ports:
      - 11633:11633
    command: --provisioning-file /app/provisioning.yaml
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:11633"]
      interval: 1s
      timeout: 3s
      retries: 60
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      QUALITYTRACE_DEV: ${QUALITYTRACE_DEV}

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 60

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.59.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "55679:55679"
      - "4317:4317"
      - "8888:8888"
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./local-config/collector.config.yaml:/otel-local-config.yaml
    depends_on:
      - quality-trace
