receivers:
  awsxray:
    transport: udp

processors:
  batch:

exporters:
  awsxray:
    region: ${AWS_REGION}
  otlp/quality-trace:
    endpoint: quality-trace:4317
    tls:
      insecure: true

service:
  pipelines:
    traces/quality-trace:
      receivers: [awsxray]
      processors: [batch]
      exporters: [otlp/quality-trace]
    traces/awsxray:
      receivers: [awsxray]
      exporters: [awsxray]
