apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tracetest.fullname" . }}
  labels:
    {{- include "tracetest.labels" . | nindent 4 }}
data:
  config.yaml: |-
    poolingConfig:
      {{- toYaml .Values.poolingConfig | nindent 6 }}
    googleAnalytics:
      enabled: {{.Values.analytics.enabled}}
    postgres:
    {{- if .Values.postgresql.enabled }}
      host: {{ include "tracetest.postgresql.fullname" . }}
      user: {{.Values.postgresql.auth.username}}
      password: {{.Values.postgresql.auth.password}}
    {{- else }}
      host: {{ .Values.externalPostgresql.host }}
      user: {{ .Values.externalPostgresql.qualitytrace.username }}
      {{- if not .Values.externalPostgresql.qualitytrace.existingSecret }}
      password: {{ .Values.externalPostgresql.qualitytrace.password }}
      {{- else }}
      password: $DB_PASSWORD
      {{- end }}
    {{- end }}
      port: 5432
      params: sslmode=disable
    telemetry:
      {{- toYaml .Values.telemetry | nindent 6 }}
    server:
      {{- toYaml .Values.server | nindent 6 }}
  provisioning.yaml: |-
    {{- toYaml .Values.provisioning | nindent 4 }}
---
