version: '3'
services:
  simple-go-service:
    image: simple-go-service
    platform: linux/amd64
    build: ./simple-go-service
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 8080:8080
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - OTEL_SERVICE_NAME=simple-go-service
    depends_on:
      otel-collector:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/heartbeat"]
      interval: 1s
      timeout: 3s
      retries: 60

  quality-trace:
    image: intelops/quality-trace:${TAG:-latest}
    platform: linux/amd64
    volumes:
      - type: bind
        source: ./quality-trace/quality-trace.config.yaml
        target: /app/quality-trace.yaml
      - type: bind
        source: ./quality-trace/quality-trace.provision.yaml
        target: /app/provisioning.yaml
    ports:
      - 11633:11633
    command: --provisioning-file /app/provisioning.yaml
    depends_on:
      postgres:
        condition: service_healthy
      otel-collector:
        condition: service_started
      jaeger:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:11633"]
      interval: 1s
      timeout: 3s
      retries: 60
    environment:
      QUALITYTRACE_DEV: ${QUALITYTRACE_DEV}

  postgres:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    healthcheck:
      test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
      interval: 1s
      timeout: 5s
      retries: 60
    ports:
      - 5432:5432

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.83.0
    command:
      - "--config"
      - "/otel-local-config.yaml"
    volumes:
      - ./quality-trace/collector.config.yaml:/otel-local-config.yaml
    ports:
      - 4317:4317
    depends_on:
      jaeger:
        condition: service_started

  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: unless-stopped
    ports:
      - 16686:16686
      - 16685:16685
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ["CMD", "wget", "--spider", "localhost:16686"]
      interval: 1s
      timeout: 3s
      retries: 60
