postgres:
  host: quality-trace-postgres
  user: postgres
  password: postgres
  port: 5432
  dbname: postgres
  params: sslmode=disable

telemetry:
  exporters:
    collector:
      serviceName: quality-trace
      sampling: 100 # 100%
      exporter:
        type: collector
        collector:
          endpoint: otelcol:4317

server:
  telemetry:
    exporter: collector
