receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  azuremonitor:
    instrumentation_key: ${INSTRUMENTATION_KEY}
  otlp/quality-trace:
    endpoint: quality-trace:4317
    tls:
      insecure: true

service:
  pipelines:
    traces/quality-trace:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/quality-trace]
    traces/appinsights:
      receivers: [otlp]
      exporters: [azuremonitor]
