version: '3'
services:

    quality-trace:
        image: intelops/quality-trace:${TAG:-latest}
        volumes:
            - type: bind
              source: ./quality-trace-config.yaml
              target: /app/quality-trace.yaml
        ports:
            - 11633:11633
        extra_hosts:
          - "host.docker.internal:host-gateway"
        depends_on:
            postgres:
                condition: service_healthy
        healthcheck:
            test: ["CMD", "wget", "--spider", "localhost:11633"]
            interval: 1s
            timeout: 3s
            retries: 60
        environment:
            TRACETEST_DEV: ${TRACETEST_DEV}

    postgres:
        image: postgres:14
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
        healthcheck:
            test: pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"
            interval: 1s
            timeout: 5s
            retries: 60
        ports:
            - 5432:5432
